### ISSUE TITLE
Utilize WebGL conformance suites in test automation

### ISSUE THREAD

**Issue by mrautio** [mrautio/duktape-webgl#1]
https://github.com/KhronosGroup/WebGL/tree/master/conformance-suites

Probably requires some small XHTML parsing capability in order to execute the test sets. So separate program from the actual bootstrap would be the best.

**Comment by mrautio-p** [comment]
Initial version done, a lot of stuff need to be done still:

- ECMAScript 6 -> 5 conversion of the test cases so that it's Duktape compatible
- Increase passing test coverage
- Upload test results as artifacts in github actions

**Comment by mrautio** [comment]
Initial version done, a lot of stuff need to be done still:

- ECMAScript 6 -> 5 conversion of the test cases so that it's Duktape compatible
- Increase passing test coverage
- Upload test results as artifacts in github actions

**Comment by mrautio** [comment]
https://github.com/mrautio/duktape-webgl/commit/f8dfcccab75dff6777dfcbce4e956e3450c8e13c
